### ISSUE TITLE
Storing comments

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#11] opened 2019-03-11 18:36 UTC
I would like to store comments in the `website-copy` repository, as I want the responsibility for the language of the comments to rest with the website-copy team not the analyzers teams.

I would like to suggest we take the following approach to this.

- In the analyzers, comments are returned as strings (e.g. `ruby.general.use_class_not_module` or `ruby.two_fer.use_string_format_not_kernel_format`)
- In website copy, we have a markdown file for each each string, where a `.` is mapped to a directory. e.g. `ruby/general/use_class_not_module.md`.
- In the analyzer, we have a `comments_used.yaml` file, which lists all the comments used. PRs will be blocked unless there is a merged comment file in website-copy that matches everything in this yaml file.

I understand there's indirection here with two repos, but I think I care enough about having the website-copy team manage copy that I'm happy to put up with the slight extra pain.

Thoughts?

**Comment by ErikSchierboom** [comment] 2019-03-11 18:39
Oh I think this is fantastic. I really, really don't want to be the one writing the comments, as I'm sure others can do that much better!

**Comment by SleeplessByte** [comment] 2019-03-11 18:39
As member of @exercism/website-copy-reviewers and as maintainer of @exercism/javascript , I support this 100%. 

(Tagged so those who will be reviewing actually can join this discussion).

**Comment by iHiD** [comment] 2019-03-11 18:41
(cc @exercism/website-copy in general too)

**Comment by kytrinyx** [comment] 2019-03-11 20:43
I 100% agree that this is how it should be done ✨

**Comment by cmccandless** [comment] 2019-03-12 13:02
As far as managing the gap between the 2 repos: would it simplify deployment to add `website-copy` as a submodule, or is that adding further complication?

**Comment by cmccandless** [comment] 2019-03-12 13:05
Also, making a note here that the following documentation will need to be updated if this concept is implementing:
- https://github.com/exercism/automated-mentoring-support/blob/master/docs/interface.md#comments

**Comment by iHiD** [comment] 2019-03-12 13:37
The comments themselves won't need to go in the analyzer repo so I don't think there's a gap. They'll be joined up in the website itself.

**Comment by sshine** [comment] 2019-03-12 14:02
Having comments in a shared format makes it easier to detect when one track can inherit a hint from another track: The hint text may be almost or exactly the same, and the analyzer may differ. So if you already have the one, you can create simple, repetitive tasks to add analyzers for things derivable from other tracks.

But if I'd like to run a traditional linter and show the student its output, because maybe they didn't install that linter and didn't receive these free tips, then I might have to create a message type for every possible thing the linter has to say, which is not something I wish to do. And some smart linters might even print stuff that refers to specific variables and functions. These messages would require format variables and are probably not guaranteed to have easy equivalents in other languages.

So I'll say that such a format and placement as this is not directly compatible with traditional language linters.

So if we go with having messages in website-copy for our custom exercise-specific linters, we could just enable traditional language-specific linters that aren't integrated with website-copy and we'll be happy to have both.

**Comment by tehsphinx** [comment] 2019-03-12 22:23
I think this approach is generally very good! The analyzer code should not worry about the comments content or formulation.

Just a few observations I have made with exalysis:
- From different people changing a comments wording it happened (in rare cases) that a comment that was added on several slightly different cases was changed in a way that it didn't really fit one of the cases any more. Sometimes the people formulating a comment might not have all the information to formulate it "correctly".
- To make some comments more clear for the student we sometimes used placeholders to e.g. insert a variables name. This can however greatly improve difficulty for the people maintaining the comments (apart from the extra work to extract the variable name) if it is not clear what a placeholder stands for. If placeholders are considered that might need to be documented in the vicinity of the comment.

**Comment by ErikSchierboom** [comment] 2019-03-13 07:52
> To make some comments more clear for the student we sometimes used placeholders to e.g. insert a variables name.

Yes, this is something that perhaps requires some additional thought on how to handle this. A comment stating: "You can convert the method to an expression body" is slightly less helpful than "You can convert method X to an expression body".

**Comment by SleeplessByte** [comment] 2019-03-13 11:02
I think named placeholders are usually pretty good; rarely need the gettext description.

**Comment by tehsphinx** [comment] 2019-03-13 13:00
@SleeplessByte: not every language might have named placeholders.

**Comment by SleeplessByte** [comment] 2019-03-13 15:32
That doesn't matter. The idea is to have an interface where the analyzer returns the a string that will be used as template. If that api is changed to something like "the analyzer returns a string and a dictionary" / similar, only `ruby` needs to have named placeholders. And it does.

**Comment by tehsphinx** [comment] 2019-03-13 16:29
You are right. Missed that.

**Comment by iHiD** [comment] 2019-03-19 16:43
Everyone happy with me supporting the following syntaxes?

I personally will be using (1) and (4) in Ruby. But I imagine (4) is harder in some languages.

```json
{
  "status": "approve_with_comment",
  "comments": ["ruby.general.some_message", "ruby.two_fer.some_specific_message"]
}
```


```json
{
  "status": "approve_with_comment",
  "comments": [["ruby.general.some_message"], ["ruby.two_fer.some_specific_message"]]
}
```


```json
{
  "status": "approve_with_comment",
  "comments": [["ruby.general.some_paramaterised_message" "param1", "param2"], ["ruby.two_fer.some_specific_message"]]
}
```

```json
{
  "status": "approve_with_comment",
  "comments": [["ruby.general.some_paramaterised_message", "param1", "param2"], "ruby.two_fer.some_specific_message"]
}
```

**Comment by ErikSchierboom** [comment] 2019-03-19 16:54
Looking good. I will probably be using 3, but I'll see if I can get things working using scenario 4.

**Comment by iHiD** [comment] 2019-03-19 17:18
Yeah. I figured for C# 3 would be easier. I'll guard for all 4 scenarios so just whatever makes your life the easiest is fine by me.

**Comment by ErikSchierboom** [comment] 2019-03-19 17:28
Awesome!

**Comment by tehsphinx** [comment] 2019-03-19 19:20
Looks good to me. I think I will be using (4). Implementing some custom json marshalling 😄

**Comment by SleeplessByte** [comment] 2019-03-19 22:05
I would prefer _named_ arguments. 

Positional arguments mean that the analyzers break if someone doesn't change the order correctly on website copy; plus it means you need to see the analyzer to understand what is meant in order to write the copy.

Especially that last part is important for non-automation-maintainer-written notes.

Instead:

```json
{
  "status": "approve_with_comment",
  "comments": [
    ["ruby.general.some_paramaterised_message", { "foo": "param1", "bar": "param2" }],
    "ruby.two_fer.some_specific_message"
  ]
}

**Comment by sshine** [comment] 2019-03-20 03:10
As an extension to @SleeplessByte's comment, I would prefer if the parameterised comment was not constructed as a list,

    ["ruby.general.some_paramaterised_message", { "foo": "param1", "bar": "param2" }]

since this provides for bad naming (`->[0]`, `->[1]`, which was which?) when extracting these values, and another source of errors when the list is not long enough (what was missing?). Rather,

    {
      "comment": "ruby.general.some_paramaterised_message",
      "params": { "foo": "param1", "bar": "param2" }
    }

along with the parameterless

    "ruby.two_fer.some_specific_message"

I assume that we won't have an exercise called "general".

**Comment by ErikSchierboom** [comment] 2019-03-20 07:11
I really like @sshine's proposal! Two options:

1. Just a plain string: `"ruby.two_fer.some_specific_message"`
1. An object with two keys: `"comment"` and `"params"`.

**Comment by SleeplessByte** [comment] 2019-03-20 08:06
@sshine proposal is actually what I currently output (with slightly different keys).

**Comment by Stargator** [comment] 2019-03-20 14:26
@iHiD I may be missing some context, what are the comments commenting on?

**Comment by iHiD** [comment] 2019-03-20 14:46
@Stargator What is wrong with the solution and needs fixing.

**Comment by Stargator** [comment] 2019-03-20 15:14
@iHiD I have no problem with the solution, I guess I just don't what the comments are that this issue is referring to.

Essentially, I don't know what the problem is, so I don't have an opinion on the solution.

What I think of when I think of "comments" are the comments left by students and mentors on solution pages. If not that, then are the comments the hints mentors/maintainers leave as part of the [website-copy repo](https://github.com/orgs/exercism/teams/website-copy-dart/members)?

**Comment by ErikSchierboom** [comment] 2019-03-20 15:22
@Stargator This issue is referring to the comments that will be made automatically by the automated mentoring functionality that is being worked on.

**Comment by Stargator** [comment] 2019-03-20 18:52
@ErikSchierboom Okay, thank you.

**Comment by ErikSchierboom** [comment] 2019-03-22 20:35
@iHiD Do you have any comments on the format suggested by @sshine? It is slightly different from your proposed format, but not by much.

**Comment by tehsphinx** [comment] 2019-03-23 19:48
Note: latest go-analyzer uses the format suggest by @sshine. Of course I can change that should it not be the consensus we come to. Here two examples:
https://github.com/exercism/go-analyzer/blob/master/tests/two-fer/6/expected.json
https://github.com/exercism/go-analyzer/blob/master/tests/two-fer/9/expected.json

**Comment by SleeplessByte** [comment] 2019-03-24 00:55
`typscript-analyzer` and `javascript-analyzer` both output the proposed format with external template string references when running with `--templates` now.

**Comment by ErikSchierboom** [comment] 2019-03-26 09:54
@iHiD If you find some free time, would you mind chipping in with your thoughts on the above suggested format?

**Comment by iHiD** [comment] 2019-03-29 17:56
The following will be valid:

```
"comments": [
  {
    "comment": "ruby.general.some_paramaterised_message",
    "params": { "foo": "param1", "bar": "param2" }
  }, 
  {
    "comment": "ruby.general.some_paramaterised_message"
  },
  "ruby.general.some_paramaterised_message"
]
```

**Comment by iHiD** [comment] 2019-03-29 17:56
Could someone PR this to the interface please :)

**Comment by cmccandless** [comment] 2019-03-29 17:59
> Could someone PR this to the interface please :)

I'll have it up in a moment.

**Comment by ErikSchierboom** [comment] 2019-03-29 18:00
Great!

**Comment by SleeplessByte** [comment] 2019-04-01 17:23
This is now in #27 and merged, so I think this can be closed? Perhaps further discussion about the structure in `website-copy` etc could be in a new issue?

**Closed as completed** 2019-04-01 18:37 UTC
